### ISSUE TITLE
Example with redux.js?

### ISSUE THREAD

**Issue by kokujin** [pakastin/frzr#12]
Would the be an example with redux.js soon? Thanks

**Comment by pakastin** [comment]
Sorry, I've never used redux.. Is there some specific issue with redux and frzr?

**Comment by kokujin** [comment]
No issue, just curiosity since redux.js seems to be the hottest thing in the react + flux world at the moment

**Comment by pakastin** [comment]
Ok, I'll leave this open if someone wants to make an example..

**Comment by pakastin** [comment]
update: FRZR works great with redux. I've used it with web workers, which is almost the same thing (you send actions with `worker.postMessage(data)` and receive them with `worker.addEventListener('message', function (e) {})`

Here's an example:
http://pakastin.fi/frzr-test
http://pakastin.fi/frzr-test/main.js (main app – just deals with the DOM)
http://pakastin.fi/frzr-test/worker.js (web worker for data handling – think this as Redux)

**Comment by pakastin** [comment]
If you write this little snippet to the browser's console, you can see the messages between the main app and the worker:
```
api.addEventListener('message', function (e) {
  console.log(e.data);
});

var postMessage = api.postMessage;
api.postMessage = function (data) {
  console.log(data);
  postMessage.call(this, data);
}
```

**Comment by pakastin** [comment]
I still haven't tried Redux, but here is a redux-like example with web worker:
https://github.com/pakastin/worker-example
https://worker-example-pakastin.c9users.io

;)

**Comment by pakastin** [comment]
You can search from mixed fields separated with space (like "gmail.com finland").

Also notice the example shows items while they are still loading. It also stays responsive while typing - even though it searches 50 000 items simultaneously!
