### ISSUE TITLE
Upgrading the to-do sample to be aligned with the current release of frzr.

### ISSUE THREAD

**Issue by esfand** [pakastin/frzr#16]
to be aligned with the current release of frzr.

**Comment by pakastin** [comment]
This is coming soon!

**Comment by pakastin** [comment]
The reason it's taken so long is, that this time I want to make it TodoMVC-compliant for better comparing with other frameworks..

**Comment by esfand** [comment]
Great idea.  Thanks.

**Comment by pakastin** [comment]
I actually removed the project. Will make new one in some point..
