### ISSUE TITLE
{ isDefined } from utils

### ISSUE THREAD

**Issue by jwarnox** [pakastin/frzr#19]
Is this a bug or am I missing something, line: https://github.com/pakastin/frzr/blob/master/src/utils.js#L9

When I ran this in the console I got true? which is wrong as x is an undefined var
```javascript
var x;
function isDefined (check) {
  return typeof check !== 'undefined' || check !== null;
};
isDefined(x);
> true
```

but using a logical AND (&&) it works!

```javascript
var x;
function isDefined (check) {
  return typeof check !== 'undefined' && check !== null;
};
isDefined(x);
> false
isDefined();
> false
```

**Comment by pakastin** [comment]
oh, thanks! I fixed it to `translate.js` (the only place it's used), and removed the helper – it wasn't even exported from `index.js`..

https://github.com/pakastin/frzr/commit/d8209661954b674aa67403ccaf3ffa49c07a76be

**Comment by jwarnox** [comment]
Cool - https://github.com/pakastin/frzr/blob/master/src/translate.js#L3 is redundant now but rollup is smart enough not to try and import it

**Comment by pakastin** [comment]
Oh yeah, I'll remove that also. Thank you so much for reporting the issue! 👍

**Comment by jwarnox** [comment]
Your welcome and looking forward to Part 2 in your blog series on FRZR !

**Comment by pakastin** [comment]
I'm working on it.. Still haven't figured out precisely what FRZR really is and where it should go - easier to use or more towards minimalism and thinner DOM wrap.

Tough questions, and it feels like as I'm writing the post, I'm somehow locking the specs, if you know what I mean. Another thing is that English is not my mother tongue and I constantly feel that I'm writing bad English, repeating words etc.. Never written a blog before, but I'm learning.

Thank you for the support! ;)
