### ISSUE TITLE
FRZR demo 5 color selection contains a car

### ISSUE THREAD

**Issue by ahvonenj** [pakastin/frzr#21]
http://codepen.io/pakastin/pen/MKpMyM

1. Select `colors` from left menu
2. Notice `Volkswagen` in the right menu

???

Clearly this should not be the case as:

```
// define constants
var COLORS = ['Red', 'Green', 'Blue'];
var CARS = ['Audi', 'BMW', 'Tesla', 'Volkswagen'];
```

The colors list does not contain cars.

**Comment by pakastin** [comment]
Oh, I must have broken it in the last update – just a sec..

**Comment by pakastin** [comment]
Fixed now. I rolled back to the previous version, which breaks viewlist's `preremove` -event. I will fix that soon..

**Comment by pakastin** [comment]
Thanks for letting know! 👍
