### ISSUE TITLE
non-string child throws

### ISSUE THREAD

**Issue by lhorie** [pakastin/frzr#22]
```javascript
var el = frzr.el("div", {id: "a"}, 1)
```

expected: `<div id="a">1</div>`
actual: `frzr.js:180 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

This also happens for booleans and arrays

**Comment by pakastin** [comment]
Good point - thanks for bringing this out! I'll fix it tomorrow (it's 10:30pm in Finland)..

**Comment by pakastin** [comment]
Fixed now!

**Comment by pakastin** [comment]
Oh, I will reopen this until I add Array support..

**Comment by pakastin** [comment]
Now also Array is supported, closing.

**Comment by pakastin** [comment]
@lhorie btw. check out: https://codepen.io/pakastin/pen/xVWZrZ ;)

**Comment by pakastin** [comment]
Another version: https://codepen.io/pakastin/pen/aNYZee

There's no `position: absolute`, everything's positioned with CSS (`display: inline-block`). You can even resize the window while animating and it will still work like expected.. :P
