### ISSUE TITLE
mounted lifecycle hook triggered before actual DOM mount?

### ISSUE THREAD

**Issue by talmobi** [pakastin/frzr#24]
Hi,

Seems like the mounted lifecycle hook is triggered just before the actual mounting takes place? My elements offsetWidth's etc are 0. Wrapping this.mounted with a setTimeout of 0 delay seems to fix the issue - thoughts?

Working sample of issue: https://github.com/talmobi/frzr_issue24

clone it and open index.html

Things to see:

1. Blank page on initial page load - charts (realtimechart.js) are not displayed properly. In fact they work just fine, but their size is 0 so practically invisible (since it's automatically set to offsetWidth (basically window.innerWidth) on init (aka mount))

2. If you resize the page, the window resize event listeners (that the charts attach on init, aka, when furze this.mounted is called) are triggered and correctly resizes the charts and thus the charts are now visible and working perfectly.

3. If you wrap the "initRealtieCharts" function inside frzr this.mounted (line 63-64 in index.html) with a setTimeout of 0 (aka immediately set inside event queue) it will work just perfectly on initial page load. Almost as if the this.monted is trigger just before the element has actually been inserted to the DOM.

4. I could be wrong and missing something obvious - but I tested the same chart init function with domvm and react (attached to their respective mounted lifecycle hooks) and they worked fine.

Thoughts? @pakastin

**Comment by pakastin** [comment]
Hi!

There's actually two lifecycle "hooks", mounting and mounted. They should be in right order: https://github.com/pakastin/frzr/blob/master/src/mount.js#L26

But I'll check this out.. 👍

**Comment by pakastin** [comment]
Actually I think the issue is that child elements get mounted after the parent element.. I'll confirm that later when I'm on my laptop.

**Comment by pakastin** [comment]
Yeah, maybe the canvas isn't mounted just yet when it's parent mounts.. You could actually attach to canvas's mounted hook and it should work?

**Comment by pakastin** [comment]
Hmm.. Still seems a bit weird though, because children should be mounted at init phase actually. I have to take a better look 😎

**Comment by pakastin** [comment]
Now I know the issue. The difference between FRZR and vdom-based view libraries is, that FRZR creates real HTML elements and mounts them immediately when they're attached to each other. So when you create a tree of elements, the lower branches are mounted immediately, so when you attach the tree to the DOM, only one DOM layout is triggered, which makes the performance better.

Vdom on the other hand creates the structures virtually first and when you mount them, the mount events get triggered. It might also reverse mounting, but it also have to keep track of the branches, which is more complex.

Makes sense? 😊

**Comment by pakastin** [comment]
Good that you brought this up - I'm creating new websites for FRZR and there should be a doc for lifecycle events. So thank you! 👍

**Comment by talmobi** [comment]
Hi again,

Yeah you're right. The issue is fixed by initialising the charts (canvases) on the parent element (https://github.com/talmobi/frzr_issue24/blob/master/app.js#L85-L93) calling each charts init (used to be this.mounted) function https://github.com/talmobi/frzr_issue24/blob/master/app.js#L61-L67

I think the issue is how HTMLElement.offsetWidth is calculated - it's null on first mount, 0 on every succeeding mount until after parent has mounted (dashboard).

So the mounted events are triggered pretty much directly on mount - even before the parent has mounted properly.

Would it be better/more intuitive to triggered the lifecycle events of children after or within (which is kind I'm doing now "manually") their parent - I don' t know. The actual mounting worked perfectly - it's just that some of the HTMLElement attributes weren't caught up with what I was thinking of doing.

Maybe it's better as it is though, it's more hands on and less magic - even though I'm used to the other kind of lifecycle hook magic. All I'm saying is it could be unintuitive for some use cases.

I like it - will try out frzr in my projects! Nice work!
