### ISSUE TITLE
How to have dynamic lists with some different siblings

### ISSUE THREAD

**Issue by hville** [pakastin/frzr#26]
Hi. 
Still struggling with Lists. I use tables and lists a lot and a common requirement is to have a first and/or last item that is different from the dataset. example:
```
el('tr', tdSelector, tdValues, tdSum)
```
Using `lists` for `tdValues` overwrites all children so it is not an option and wrapper elements are not always possible.

What would be the recommend pattern for this?

**Comment by pakastin** [comment]
I'm using this kind of aproach: https://github.com/lhorie/frzr-dbmon/blob/gh-pages/frzr/app.js#L38:L50
You can use `index` value or figure out the data type.. Or custom render the List with `setChildren(tr, [tdSelector, tdValues.views, tdSum]);`..

The issue with having mixed views and lists is, that if the list is empty, you would need a placeholder for the list and I think it's a bit of a hack..

**Comment by hville** [comment]
I think it might be simpler if you had a more generic `Group` type that would be the basis for different implementations (e.g. `Group:()=>{views, update, parent}`). The current `List` constructor is really designed to optimize arrays of objects and could be optional, making FRZR even smaller. Users could extend `Group` to define other implementations for Tuples, Arrays or Matrices. `List` would be an extension of `Group`, allowing all implementation to have the [same mounting behaviour in mount.js](https://github.com/pakastin/frzr/blob/master/src/mount.js#L41:L43) where the parent and children would be set (ie. `if (child instance of Group)` or `if (child.views && child.hasOwnProperty('parent'))`).

Right now I have to do this in 2 steps:
```
myGroup = group(view1, new List(View2), view3)
this.el = el('tr', myGroup.views)
this.update = group.update.bind(group)
```

**Comment by talmobi** [comment]
Wouldn't you be able to use setChildren for that? I've used setChildren for all my list type things so far and it has worked fine (haven't used List at all).

**Comment by pakastin** [comment]
@talmobi is right, List is just an optional helper. But I will investigate the group suggestion..

**Comment by pakastin** [comment]
Thanks again for great ideas! 👍

**Comment by hville** [comment]
@talmobi great. Everything is obvious when you know the answer. Thanks.

**Comment by pakastin** [comment]
Great that you found a solution! 😎 I will get back to this "group" idea – I'm on a small holiday right now..

I'm thrilled you've found FRZR useful, and am happy to help you out! You can also join Gitter (pakastin/frzr) if you want to just chat about FRZR. Or Koodiklinikka Slack channel #javascript (https://koodiklinikka.fi).
