### ISSUE TITLE
lifecycle events and custom attributes

### ISSUE THREAD

**Issue by sloschi** [pakastin/frzr#27]
The customAttribute example uses the element.mounted callback to add a css class. I think this should be a discouraged behaviour. If you define another custom attribute which also uses this lifecycle callback and use both this attributes on the same element, it will overwrite the other.

It would be nice if we could have multiple callbacks for mounted ;)

**Comment by pakastin** [comment]
I fixed the example: https://github.com/pakastin/frzr/releases/tag/v0.18.0

FRZR used to have `Observable`, but it required extending from the class and was a usual cause for memory leaks. It's safer to always handle lifecycle events inside the View itself..

Makes sense? :)

**Comment by sloschi** [comment]
great, thanks!
